feat: migrate integration tests to canonical/charm-ci (#136)

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -6,43 +6,29 @@ on:
   - cron: "0 15 * * SAT"
 
 jobs:
-  integration-tests-juju-3:
-    uses: 
-      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
+  integration-test:
+    uses: canonical/charm-ci/.github/workflows/integration-test.yml@v0.0.1-alpha.5
     permissions:
       contents: read
       packages: write
-      pull-requests: write
+      actions: read
     secrets: inherit
     with:
-      trivy-fs-enabled: false
-      trivy-image-config: "trivy.yaml"
-      self-hosted-runner: true
-      self-hosted-runner-label: "edge"
-      juju-channel: '3/stable'
-      channel: '1.34-strict/stable'
-      with-uv: true
-  integration-tests:
-    uses: 
-      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
-    permissions:
-      contents: read
-      packages: write
-      pull-requests: write
-    secrets: inherit
-    with:
-      trivy-fs-enabled: true
-      trivy-image-config: "trivy.yaml"
-      self-hosted-runner: true
-      self-hosted-runner-label: "edge"
-      juju-channel: '4/stable'
-      channel: '1.34-strict/stable'
-      with-uv: true
-  allure-report:
-    if: ${{ !cancelled() && github.event_name == 'schedule' }}
+      working-directory: .
+  required_status_checks:
+    name: Required Integration Test Status Checks
+    runs-on: ubuntu-latest
     needs:
-    - integration-tests-juju-3
-    - integration-tests
-    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
-    permissions:
-      contents: write
+      - integration-test
+    if: always() && !cancelled()
+    timeout-minutes: 5
+    steps:
+      - name: Check integration-test status
+        run: |
+          RESULT="${{ needs.integration-test.result }}"
+          if [ "$RESULT" = "success" ] || [ "$RESULT" = "skipped" ]; then
+            exit 0
+          else
+            echo "integration-test failed with status: $RESULT"
+            exit 1
+          fi
